name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Pipeline is running because you pushed to main"
